name: Deploy and Build V75 Online

# Trigger the workflow on push and pull request events on the dev branch
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy project files via SCP
        run: |
          scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/debian/Documents/v75

  build:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "\
          cd /home/debian/Documents/v75/ && \
          composer install --no-interaction --prefer-dist --optimize-autoloader && \
          php artisan migrate --force && \
          fuser -k 8000/tcp && \
          php artisan serve --host 0.0.0.0 --port 8000 &> /dev/null &"
