name: Deploy and Build V75 Online

# Trigger the workflow on push and pull request events on the dev branch
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      
jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "echo 'SSH setup complete'"

      - name: Copy project files
        run: |
          scp -r ./* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/debian/Documents/v75

  build:
    needs: setup-ssh
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd /home/debian/Documents/v75/ && \
            composer install --no-interaction --prefer-dist --optimize-autoloader && \
            php artisan migrate --force && \
            fuser -k 8000/tcp && \
            php artisan serve --host 0.0.0.0 --port 8000 &> /dev/null &"
