name: Deploy and Build V75 Online

# Trigger the workflow on push and pull request events on the dev branch
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            scp -r ./* debian@152.228.173.31:/home/debian/Documents/v75
  build:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/debian/Documents/v75/
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            fuser -k 8000/tcp
            php artisan serve --host 0.0.0.0 --port 8000 &> /dev/null &
    
